import type { BasicFactPredicate } from "../data/evidence";

export interface DiligenceTopic { id: string; title: string; predicate: BasicFactPredicate; question: string }
export const COMPANY_DILIGENCE_TOPICS: readonly DiligenceTopic[] = [
  { id: "mechanism", title: "How it works", predicate: "product", question: "What specific mechanism implements the product? For privacy products distinguish mixer or shielded pool design from cryptographic primitives: ZK proofs, FHE, MPC, TEE, stealth addresses or hybrids can coexist. Identify which primitive does which job. Cite technical documentation, code or papers; a marketing word is only a claim." },
  { id: "privacy_scope", title: "Privacy guarantees and trust", predicate: "product", question: "For a privacy product, exactly which sender, receiver, amount, balance, metadata or computation is hidden, from whom, and under what assumptions? Identify operator, key-management, trusted-setup, relayer, custody and timing-correlation dependencies. For other products document equivalent operational constraints. Do not infer guarantees from the technology name." },
  { id: "implementation", title: "What is implemented", predicate: "product", question: "Which claimed capabilities are deployed, testnet-only, prototype, audited or planned? Link the exact version, contracts, repository and audit scope where available. Do not treat a roadmap, a repository or an audit of another component as proof of a live feature." },
  { id: "claimed_edge", title: "Their claimed edge", predicate: "product", question: "What technical or business advantage does the company itself claim? Identify a specific named capability, integration, distribution asset, proprietary data, cost benefit or user advantage. Preserve the attributed source and exact passage; a claim is not demonstrated performance." },
  { id: "edge_evidence", title: "Evidence for the edge", predicate: "traction", question: "What dated measurements support a claimed advantage, under which workload, baseline, cost and sample? Look for reproducible benchmarks, paid adoption, retention, distribution or switching evidence. Report the exact metric and source, separating company self-report from independent validation." },
  { id: "alternatives", title: "Alternatives and replication", predicate: "product", question: "Which named alternatives solve the same customer problem, and what does sourced evidence say about differences or the effort to replicate this product? Include dates and comparable configurations; do not call something unique merely because no comparison was found." },
];
export const PERSON_DILIGENCE_TOPICS: readonly DiligenceTopic[] = [
  { id: "identity_links", title: "Public identity and aliases", predicate: "official_identity", question: "Which names, aliases and professional profiles has this person publicly connected to this exact account? Preserve the public identity and proof link. If it is not established, retain the pseudonym. Do not use leaks, home addresses, private contacts or speculative deanonymization." },
  { id: "role_scope", title: "Role and responsibility", predicate: "current_role", question: "What is the person's current role, actual responsibility and capacity in each startup or organization? Distinguish founder, executive, employee, engineer, advisor, investor principal and partner; record start/end dates and verify the employer's website and activity." },
  { id: "venture_history", title: "Venture history", predicate: "track_record", question: "For each prior venture, what did this exact person contribute, when, with whom, and what happened to it? Separate acquisition, closure, inactivity, failure and proven misconduct; disclose unknown outcomes and avoid survivorship bias." },
  { id: "collaborators", title: "Recurring collaborators", predicate: "partnership", question: "Which people co-founded or directly collaborated with this subject, on which ventures and dates, and which are involved again today? Include publicly linked aliases and exact profile or company URLs only when the source binds them. A follow, shared investor or mention is not a collaboration." },
  { id: "engineering", title: "Engineering contribution", predicate: "repository", question: "For an engineer or coding founder, what GitHub profiles, original contributions, shipped repositories, release history and maintenance are publicly attributable to this person? Distinguish their contribution from the whole organization's code, forks, stars and private work." },
  { id: "investment_record", title: "Investment responsibility", predicate: "investor", question: "For an investor, which investments, board roles and realized outcomes are personally attributable, in what principal/partner/committee capacity? Separate the individual's responsibility from the firm's portfolio, paper markups and fund claims." },
  { id: "credentials", title: "Education and accolades", predicate: "education", question: "Which education and professional credentials or awards are documented, by whom and when? Distinguish attendance from graduation, nominations from wins and self-description from awarding-body confirmation." },
  { id: "military_service", title: "Relevant public service", predicate: "prior_role", question: "If relevant and publicly disclosed, what military service, dates, specialty, leadership responsibility and distinctions are documented? Cite public primary records or attributable biographies; distinguish claimed and confirmed distinctions. Do not infer character or competence from military affiliation alone." },
  { id: "public_records", title: "Public records and concerns", predicate: "legal_regulatory_event", question: "What public court, regulatory or sanctions events explicitly identify this person using more than a name, in which jurisdiction and with what current procedural status? Distinguish allegations, charges, findings, dismissal and appeal. Reddit/social reports are leads requiring primary corroboration. Never imply a comprehensive clean record from an empty search." },
  { id: "wallet_attribution", title: "Public wallet attribution", predicate: "treasury", question: "Which chain-specific wallets are publicly disclosed by or cryptographically bound to this person, with dated attribution? Identify only sourced activity and control. Transfers, clustering, exchange deposits and third-party labels do not establish personal ownership or wrongdoing." },
];
