export type ProviderKind = "evidence" | "model" | "infrastructure";
export type ProviderLifecycle = "active" | "retired" | "reserved";
export type EvidenceCategory = "Identity and people" | "Markets and projects" | "Blockchain activity" | "Safety and legal" | "Web and public records";
export type ProviderTier = "paid" | "optional" | "infra" | "keyless";

export interface ProviderCatalogEntry {
  id: string;
  label: string;
  powers: string;
  limits: string;
  source: string;
  tier: ProviderTier;
  kind: ProviderKind;
  lifecycle: ProviderLifecycle;
  category?: EvidenceCategory;
  env?: string[];
  alternativeEnv?: string[];
  alsoEnv?: string[];
  availableWithoutCredential?: boolean;
  live?: "github";
}

export const PROVIDER_CATALOG: readonly ProviderCatalogEntry[] = [
  {
    id: "grok",
    label: "Grok (xAI)",
    powers: "Reasoning, extraction, image review, and live web and X discovery",
    limits: "A research model, not an independent evidence source. Report claims still require captured sources.",
    source: "console.x.ai",
    tier: "paid",
    kind: "model",
    lifecycle: "active",
    env: ["XAI_API_KEY"],
  },
  {
    id: "claude",
    label: "Claude (Anthropic)",
    powers: "Optional fallback reasoning when provider fallbacks are enabled",
    limits: "A research model, not an independent evidence source.",
    source: "console.anthropic.com",
    tier: "optional",
    kind: "model",
    lifecycle: "active",
    env: ["ANTHROPIC_API_KEY"],
  },
  {
    id: "openrouter",
    label: "OpenRouter",
    powers: "Optional extraction fallback when provider fallbacks are enabled",
    limits: "A model route, not an independent evidence source.",
    source: "openrouter.ai",
    tier: "optional",
    kind: "model",
    lifecycle: "active",
    env: ["OPENROUTER_API_KEY"],
  },
  {
    id: "twitterapi",
    label: "twitterapi.io",
    powers: "X profiles, posts, account history, and follower and following relationships",
    limits: "Profile fields and social relationships are platform observations, not proof of real-world identity.",
    source: "twitterapi.io",
    tier: "paid",
    kind: "evidence",
    lifecycle: "active",
    category: "Identity and people",
    env: ["TWITTERAPI_KEY"],
  },
  {
    id: "x-api",
    label: "Official X API v2",
    powers: "Optional X profile authenticity fallback",
    limits: "Only runs when configured and does not independently verify a person's identity.",
    source: "developer.x.com",
    tier: "optional",
    kind: "evidence",
    lifecycle: "active",
    category: "Identity and people",
    env: ["X_API_BEARER"],
  },
  {
    id: "github",
    label: "GitHub",
    powers: "Public profiles, organizations, repositories, and commit-author history",
    limits: "A matching name is only a lead. ARGUS requires cross-links before treating an account as the same person.",
    source: "github.com",
    tier: "paid",
    kind: "evidence",
    lifecycle: "active",
    category: "Identity and people",
    env: ["GITHUB_TOKEN"],
    live: "github",
  },
  {
    id: "pdl",
    label: "People Data Labs",
    powers: "Professional identity and employment records",
    limits: "Third-party identity records can be stale or join the wrong namesake and must be corroborated.",
    source: "peopledatalabs.com",
    tier: "paid",
    kind: "evidence",
    lifecycle: "active",
    category: "Identity and people",
    env: ["PDL_API_KEY"],
  },
  {
    id: "farcaster",
    label: "Farcaster and Warpcast",
    powers: "Public casts and connected-wallet lookups",
    limits: "A connected wallet is a platform attribution, not proof that one person controls every linked account.",
    source: "warpcast.com",
    tier: "keyless",
    kind: "evidence",
    lifecycle: "active",
    category: "Identity and people",
  },
  {
    id: "memorylol",
    label: "memory.lol",
    powers: "Historical X handles and rebrand leads",
    limits: "Coverage is incomplete and a past handle does not prove who controlled the account at that time.",
    source: "memory.lol",
    tier: "keyless",
    kind: "evidence",
    lifecycle: "active",
    category: "Identity and people",
  },
  {
    id: "telegram",
    label: "Telegram",
    powers: "Public cross-platform handle presence checks",
    limits: "A matching handle is a lead, not identity proof.",
    source: "t.me",
    tier: "keyless",
    kind: "evidence",
    lifecycle: "active",
    category: "Identity and people",
  },
  {
    id: "web3-names",
    label: "web3.bio, ENS, and Bonfida",
    powers: "Public name-to-wallet resolution",
    limits: "Names are user-controlled labels and do not by themselves prove real-world identity.",
    source: "web3.bio",
    tier: "keyless",
    kind: "evidence",
    lifecycle: "active",
    category: "Identity and people",
  },
  {
    id: "coingecko",
    label: "CoinGecko",
    powers: "Token identity, price, market cap, supply, and market rank",
    limits: "Market data is a point-in-time provider reading. A paid key raises limits but is not required.",
    source: "coingecko.com",
    tier: "optional",
    kind: "evidence",
    lifecycle: "active",
    category: "Markets and projects",
    env: ["COINGECKO_API_KEY"],
    availableWithoutCredential: true,
  },
  {
    id: "dexscreener",
    label: "DexScreener",
    powers: "DEX pairs, liquidity, volume, and recent market activity",
    limits: "Pair data describes a venue at capture time and does not prove ownership, lock status, or safety.",
    source: "dexscreener.com",
    tier: "keyless",
    kind: "evidence",
    lifecycle: "active",
    category: "Markets and projects",
  },
  {
    id: "geckoterminal",
    label: "GeckoTerminal",
    powers: "Onchain DEX price history and OHLCV",
    limits: "Coverage depends on indexed pools and does not establish an asset's complete trading history.",
    source: "geckoterminal.com",
    tier: "keyless",
    kind: "evidence",
    lifecycle: "active",
    category: "Markets and projects",
  },
  {
    id: "defillama",
    label: "DeFiLlama",
    powers: "Protocol TVL, fees, funding rounds, governance listings, and recorded incidents",
    limits: "Curated listings are not exhaustive and company funding is kept separate from token market value.",
    source: "defillama.com",
    tier: "keyless",
    kind: "evidence",
    lifecycle: "active",
    category: "Markets and projects",
  },
  {
    id: "monid",
    label: "Monid and Akta",
    powers: "Private-company funding, leadership, and firmographic enrichment",
    limits: "A paid third-party company record can be stale or join a namesake. ARGUS requires an official-domain match.",
    source: "monid.ai",
    tier: "optional",
    kind: "evidence",
    lifecycle: "active",
    category: "Markets and projects",
    env: ["MONID_API_KEY"],
  },
  {
    id: "snapshot",
    label: "Snapshot",
    powers: "Public governance spaces and proposals",
    limits: "Snapshot records offchain voting activity, not automatic execution or legal authority.",
    source: "snapshot.org",
    tier: "keyless",
    kind: "evidence",
    lifecycle: "active",
    category: "Markets and projects",
  },
  {
    id: "helius",
    label: "Helius (Solana)",
    powers: "Solana wallet activity, deployer, funding, mint, and launch traces",
    limits: "Wallet activity does not establish beneficial ownership without independent attribution.",
    source: "helius.dev",
    tier: "paid",
    kind: "evidence",
    lifecycle: "active",
    category: "Blockchain activity",
    env: ["HELIUS_API_KEY"],
  },
  {
    id: "etherscan",
    label: "Etherscan (multichain)",
    powers: "EVM contract creation, deployer, and funding traces",
    limits: "Explorer transactions establish addresses and transfers, not the identity behind a wallet.",
    source: "etherscan.io",
    tier: "optional",
    kind: "evidence",
    lifecycle: "active",
    category: "Blockchain activity",
    env: ["ETHERSCAN_API_KEY"],
  },
  {
    id: "arkham",
    label: "Arkham",
    powers: "Wallet labels, counterparties, holdings, and risk paths",
    limits: "Labels are Arkham attributions. ARGUS reports them as such and does not treat them as identity proof.",
    source: "arkhamintelligence.com",
    tier: "optional",
    kind: "evidence",
    lifecycle: "active",
    category: "Blockchain activity",
    env: ["ARKHAM_API_KEY"],
  },
  {
    id: "gmgn",
    label: "GMGN",
    powers: "Holder cost basis, wallet tags, trader PnL, and launch-pattern readings",
    limits: "Wallet tags are GMGN assessments. The provider is best effort and its AI rating is never used.",
    source: "gmgn.ai",
    tier: "optional",
    kind: "evidence",
    lifecycle: "active",
    category: "Blockchain activity",
    env: ["GMGN_API_KEY"],
  },
  {
    id: "goplus",
    label: "GoPlus",
    powers: "Contract controls, token security flags, and holder context",
    limits: "A provider response is a captured security reading, not an audit or guarantee.",
    source: "gopluslabs.io",
    tier: "keyless",
    kind: "evidence",
    lifecycle: "active",
    category: "Safety and legal",
  },
  {
    id: "honeypot",
    label: "honeypot.is",
    powers: "EVM buy and sell simulation and honeypot indicators",
    limits: "A simulation covers the tested route and moment only. It is not a full contract audit.",
    source: "honeypot.is",
    tier: "keyless",
    kind: "evidence",
    lifecycle: "active",
    category: "Safety and legal",
  },
  {
    id: "rugcheck",
    label: "RugCheck",
    powers: "Solana holder concentration, liquidity, and provider risk flags",
    limits: "Solana only. Provider flags remain attributed to RugCheck and do not replace ARGUS checks.",
    source: "rugcheck.xyz",
    tier: "keyless",
    kind: "evidence",
    lifecycle: "active",
    category: "Safety and legal",
  },
  {
    id: "safe-browsing",
    label: "Google Safe Browsing",
    powers: "Optional site-safety reputation checks",
    limits: "No listing is not proof that a site is safe. GoPlus, URLhaus, and page checks still run without it.",
    source: "safebrowsing.google.com",
    tier: "optional",
    kind: "evidence",
    lifecycle: "active",
    category: "Safety and legal",
    env: ["GOOGLE_SAFE_BROWSING_KEY"],
  },
  {
    id: "urlhaus",
    label: "URLhaus",
    powers: "Known-malware URL feed checks",
    limits: "No match means the host was not in the captured feed, not that it is safe.",
    source: "urlhaus.abuse.ch",
    tier: "keyless",
    kind: "evidence",
    lifecycle: "active",
    category: "Safety and legal",
  },
  {
    id: "courtlistener",
    label: "CourtListener",
    powers: "US court-caption search for legal-history leads",
    limits: "Name matches are leads only. They can describe a namesake and do not establish liability.",
    source: "courtlistener.com",
    tier: "keyless",
    kind: "evidence",
    lifecycle: "active",
    category: "Safety and legal",
  },
  {
    id: "sanctions",
    label: "OFAC and OpenSanctions",
    powers: "Exact-name US and international sanctions screening",
    limits: "Name screening can miss aliases and can match a namesake. It is not legal advice.",
    source: "opensanctions.org",
    tier: "keyless",
    kind: "evidence",
    lifecycle: "active",
    category: "Safety and legal",
  },
  {
    id: "serper",
    label: "Serper (grounded search)",
    powers: "Grounded web discovery for identity and additional evidence checks",
    limits: "Search results are leads. ARGUS reopens and captures supporting pages before using a claim.",
    source: "serper.dev",
    tier: "paid",
    kind: "evidence",
    lifecycle: "active",
    category: "Web and public records",
    env: ["SERPER_API_KEY"],
  },
  {
    id: "google-news",
    label: "Google News",
    powers: "Recent public-news discovery",
    limits: "Search coverage is not exhaustive and headlines are not treated as proof without the article source.",
    source: "news.google.com",
    tier: "keyless",
    kind: "evidence",
    lifecycle: "active",
    category: "Web and public records",
  },
  {
    id: "web-archives",
    label: "Web archives",
    powers: "Historical website snapshots from Wayback Machine with Arquivo fallback",
    limits: "Archive coverage is incomplete and a missing snapshot does not prove a page never existed.",
    source: "archive.org",
    tier: "keyless",
    kind: "evidence",
    lifecycle: "active",
    category: "Web and public records",
  },
  {
    id: "rdap",
    label: "RDAP",
    powers: "Domain registration dates and registrar records",
    limits: "Registration age is not project age, and privacy services may hide registrant identity.",
    source: "rdap.org",
    tier: "keyless",
    kind: "evidence",
    lifecycle: "active",
    category: "Web and public records",
  },
  {
    id: "sec",
    label: "SEC EDGAR",
    powers: "US securities filings",
    limits: "No filing found is not proof that no company or offering exists in another jurisdiction.",
    source: "sec.gov",
    tier: "keyless",
    kind: "evidence",
    lifecycle: "active",
    category: "Web and public records",
  },
  {
    id: "supabase",
    label: "Supabase",
    powers: "Saved reports, account data, trust graph, and audit log infrastructure",
    limits: "Product infrastructure, not an outside evidence source.",
    source: "supabase.com",
    tier: "infra",
    kind: "infrastructure",
    lifecycle: "active",
    env: ["SUPABASE_SECRET_KEY"],
    alternativeEnv: ["SUPABASE_SERVICE_ROLE_KEY"],
    alsoEnv: ["SUPABASE_URL"],
  },
  {
    id: "reddit",
    label: "Reddit OAuth",
    powers: "Former community-reputation collector",
    limits: "Retired because API access was not approved. It does not run in current reports.",
    source: "reddit.com",
    tier: "optional",
    kind: "evidence",
    lifecycle: "retired",
    category: "Web and public records",
    env: ["REDDIT_CLIENT_ID", "REDDIT_CLIENT_SECRET"],
  },
  {
    id: "crunchbase",
    label: "Crunchbase",
    powers: "Former company and funding enrichment",
    limits: "Retired from the core collector. DeFiLlama and Monid and Akta cover current funding enrichment.",
    source: "crunchbase.com",
    tier: "optional",
    kind: "evidence",
    lifecycle: "retired",
    category: "Markets and projects",
    env: ["CRUNCHBASE_API_KEY"],
  },
  {
    id: "bitquery",
    label: "Bitquery",
    powers: "Credential reserved for a future EVM collector",
    limits: "Reserved only. It does not currently run or attest ARGUS reports.",
    source: "bitquery.io",
    tier: "optional",
    kind: "evidence",
    lifecycle: "reserved",
    category: "Blockchain activity",
    env: ["BITQUERY_API_KEY"],
  },
] as const;

export const ACTIVE_EVIDENCE_SOURCES = PROVIDER_CATALOG.filter(
  (provider) => provider.kind === "evidence" && provider.lifecycle === "active",
);
