// The reference set for "notable followers" — the accounts that actually matter in
// crypto, so a reverse follow-check ("does @paradigm follow this subject?") gives a
// COMPLETE, meaningful credibility signal. Followed by a top fund / a real founder /
// a known caller is a signal a bot farm can't fake.
//
// Handles are checked one-by-one via check_follow_relationship, so a wrong/renamed
// handle simply returns nothing (harmless) — the list can grow freely. Keep it
// de-duplicated (handles are lowercased on load) and grouped for maintainability.
export interface NotableAccount { handle: string; label: string }

export const NOTABLE_ACCOUNTS: NotableAccount[] = [
  // ── Venture funds / firm accounts ─────────────────────────────────────────
  { handle: "a16zcrypto", label: "VC · a16z crypto" },
  { handle: "paradigm", label: "VC · Paradigm" },
  { handle: "dragonfly_xyz", label: "VC · Dragonfly" },
  { handle: "multicoincap", label: "VC · Multicoin" },
  { handle: "VariantFund", label: "VC · Variant" },
  { handle: "FrameworkVC", label: "VC · Framework" },
  { handle: "hack_vc", label: "VC · Hack VC" },
  { handle: "PlaceholderVC", label: "VC · Placeholder" },
  { handle: "panteracapital", label: "VC · Pantera" },
  { handle: "1kxnetwork", label: "VC · 1kx" },
  { handle: "electric_capital", label: "VC · Electric Capital" },
  { handle: "robotventures", label: "VC · Robot Ventures" },
  { handle: "polychaincap", label: "VC · Polychain" },
  { handle: "coinbaseventures", label: "VC · Coinbase Ventures" },
  { handle: "binancelabs", label: "VC · Binance Labs" },
  { handle: "HashKey_Capital", label: "VC · HashKey" },
  { handle: "sequoia", label: "VC · Sequoia" },
  { handle: "USV", label: "VC · Union Square Ventures" },
  { handle: "IOSG_VC", label: "VC · IOSG" },
  { handle: "hypersphere_x", label: "VC · Hypersphere" },
  { handle: "standardcrypto", label: "VC · Standard Crypto" },
  { handle: "blockchaincap", label: "VC · Blockchain Capital" },
  { handle: "galaxyhq", label: "VC · Galaxy" },
  { handle: "DelphiVentures", label: "VC · Delphi Ventures" },
  { handle: "DCGco", label: "VC · Digital Currency Group" },
  { handle: "gumi_cryptos", label: "VC · gumi Cryptos" },
  { handle: "SygnumOfficial", label: "VC · Sygnum" },
  { handle: "L2IV", label: "VC · L2 Iterative" },
  { handle: "maven11", label: "VC · Maven 11" },
  { handle: "nascentxyz", label: "VC · Nascent" },
  { handle: "bankless_vc", label: "VC · Bankless Ventures" },
  { handle: "SpartanGroup", label: "VC · Spartan" },
  { handle: "TheSpartanGroup", label: "VC · Spartan" },
  { handle: "6thmancapital", label: "VC · 6th Man Ventures" },
  { handle: "archetypevc", label: "VC · Archetype" },
  { handle: "slowfund", label: "VC · Slow Ventures" },
  { handle: "portal_ventures", label: "VC · Portal Ventures" },
  { handle: "figmentcapital", label: "VC · Figment Capital" },
  { handle: "reforgevc", label: "VC · Reforge" },
  { handle: "foundationcap", label: "VC · Foundation Capital" },
  { handle: "castle_isl", label: "VC · Castle Island" },
  { handle: "lightspeedvp", label: "VC · Lightspeed" },
  { handle: "tribecap", label: "VC · Tribe Capital" },
  { handle: "roundtripcrypto", label: "VC · Round13" },
  { handle: "fabric_vc", label: "VC · Fabric Ventures" },
  { handle: "gsr_io", label: "market maker · GSR" },
  { handle: "wintermute_t", label: "market maker · Wintermute" },
  { handle: "jump_", label: "market maker · Jump" },
  { handle: "amberGroup_HQ", label: "market maker · Amber" },
  { handle: "cumberland_io", label: "market maker · Cumberland" },
  { handle: "flowtraders", label: "market maker · Flow Traders" },
  { handle: "mechanismcap", label: "fund · Mechanism" },
  { handle: "dcfgod", label: "fund · DCF God" },
  { handle: "arca", label: "fund · Arca" },
  { handle: "republiccrypto", label: "VC · Republic Crypto" },
  { handle: "animocabrands", label: "VC · Animoca" },
  { handle: "shima_capital", label: "VC · Shima" },
  { handle: "big_brain_hodl", label: "VC · Big Brain" },
  { handle: "collab_currency", label: "VC · Collab+Currency" },
  { handle: "roninvc", label: "VC · Ronin" },

  // ── VC partners / notable investors (individuals) ─────────────────────────
  { handle: "cdixon", label: "investor · a16z" },
  { handle: "balajis", label: "investor · Balaji" },
  { handle: "cyounessi1", label: "investor · Standard Crypto" },
  { handle: "hosseeb", label: "investor · Dragonfly" },
  { handle: "danrobinson", label: "investor · Paradigm" },
  { handle: "gakonst", label: "founder · Paradigm/Foundry" },
  { handle: "cburniske", label: "investor · Placeholder" },
  { handle: "twobitidiot", label: "founder · Messari (Ryan Selkis)" },
  { handle: "avichal", label: "investor · Electric Capital" },
  { handle: "Maria_Shen", label: "investor · Electric Capital" },
  { handle: "TarunChitra", label: "founder · Gauntlet" },
  { handle: "ljin18", label: "investor · Variant" },
  { handle: "jessewldn", label: "investor · Haun" },
  { handle: "kmoney_69", label: "investor · Placeholder" },
  { handle: "spencernoon", label: "investor · Variant" },
  { handle: "arjunblj", label: "investor · Reverie" },
  { handle: "TusharJain_", label: "investor · Multicoin" },
  { handle: "KyleSamani", label: "investor · Multicoin" },
  { handle: "santiagoroel", label: "investor · Amber/Delphi" },
  { handle: "Anup_Bagchi", label: "investor" },
  { handle: "0xMaki", label: "investor · founder (Sushi)" },
  { handle: "ChrisBurniske", label: "investor · Placeholder" },
  { handle: "RobHadick", label: "investor · Dragonfly" },
  { handle: "Rewkang", label: "investor · Mechanism" },
  { handle: "adam_tehc", label: "investor" },
  { handle: "dberenzon", label: "investor" },
  { handle: "packyM", label: "investor · Not Boring" },
  { handle: "nlw", label: "media · The Breakdown" },
  { handle: "lawmaster", label: "investor · Framework (Vance Spencer)" },
  { handle: "MikeDudas", label: "investor · 6MV" },
  { handle: "iamDCinvestor", label: "investor · ETH OG" },
  { handle: "AriDavidPaul", label: "investor · BlockTower" },
  { handle: "APompliano", label: "investor · Pomp" },
  { handle: "RaoulGMI", label: "investor · Real Vision" },
  { handle: "novogratz", label: "investor · Galaxy (Mike Novogratz)" },
  { handle: "cathiedwood", label: "investor · ARK" },
  { handle: "woonomic", label: "analyst · Willy Woo" },

  // ── Founders / builders ───────────────────────────────────────────────────
  { handle: "VitalikButerin", label: "founder · Ethereum" },
  { handle: "aeyakovenko", label: "founder · Solana" },
  { handle: "rajgokal", label: "founder · Solana" },
  { handle: "jessepollak", label: "founder · Base" },
  { handle: "haydenzadams", label: "founder · Uniswap" },
  { handle: "StaniKulechov", label: "founder · Aave" },
  { handle: "sreeramkannan", label: "founder · EigenLayer" },
  { handle: "smokey_eth", label: "founder · Berachain" },
  { handle: "0xngmi", label: "founder · DefiLlama" },
  { handle: "gabrielhaines", label: "founder" },
  { handle: "brendaneich", label: "founder · Brave" },
  { handle: "sassal0x", label: "Ethereum advocate" },
  { handle: "econoar", label: "founder · Eric Conner" },
  { handle: "drakefjustin", label: "researcher · Ethereum Foundation" },
  { handle: "dannyryan", label: "researcher · Ethereum Foundation" },
  { handle: "TimBeiko", label: "Ethereum core" },
  { handle: "epolynya", label: "researcher · rollups" },
  { handle: "el33th4xor", label: "founder · Ava Labs (Emin Gün Sirer)" },
  { handle: "zhusu", label: "founder · 3AC (Su Zhu)" },
  { handle: "MacroCephalopod", label: "founder · Reserve" },
  { handle: "robertleshner", label: "founder · Compound" },
  { handle: "kaiynne", label: "founder · Synthetix" },
  { handle: "AndreCronjeTech", label: "founder · Yearn/Fantom" },
  { handle: "bantg", label: "founder · Yearn" },
  { handle: "danielesesta", label: "founder · Wonderland/Abracadabra" },
  { handle: "kaledora", label: "founder" },
  { handle: "eric_wallach", label: "founder" },
  { handle: "0xSisyphus", label: "trader/founder" },
  { handle: "MustStopMurad", label: "founder · Memecoin thesis" },
  { handle: "shawmakesmagic", label: "founder · ai16z/eliza" },
  { handle: "everythingempt0", label: "trader/founder" },
  { handle: "0xzerebro", label: "founder · AI agent" },
  { handle: "luna_virtuals", label: "founder · Virtuals" },
  { handle: "punk9059", label: "founder" },
  { handle: "0xMert_", label: "founder · Helius" },
  { handle: "rogercrypto", label: "founder" },
  { handle: "toly", label: "founder · Solana" },
  { handle: "kayceecrypto", label: "founder" },
  { handle: "loomdart", label: "trader · OG" },
  { handle: "cobie", label: "trader · UpOnly (Cobie)" },
  { handle: "ledgerstatus", label: "trader · OG" },
  { handle: "dcfgod", label: "trader" },
  { handle: "cyrusof", label: "founder" },
  { handle: "0xdesigner", label: "builder/designer" },
  { handle: "transmissions11", label: "engineer · Paradigm" },
  { handle: "boredGenius", label: "engineer · dYdX" },
  { handle: "antonio_m_juliano", label: "founder · dYdX" },
  { handle: "0age", label: "engineer · Uniswap" },
  { handle: "haydenzadams", label: "founder · Uniswap" },
  { handle: "monosarin", label: "founder · Polymarket (Shayne Coplan)" },
  { handle: "shayne_coplan", label: "founder · Polymarket" },
  { handle: "gavofyork", label: "founder · Polkadot/Parity" },
  { handle: "rune_christensen", label: "founder · MakerDAO/Sky" },
  { handle: "kaiynne", label: "founder · Synthetix" },
  { handle: "coopahtroopa", label: "builder · music/NFTs" },
  { handle: "cryptopunk7213", label: "founder · Compound (Robert Leshner alt)" },

  // ── KOLs / callers / traders ──────────────────────────────────────────────
  { handle: "blknoiz06", label: "caller · Ansem" },
  { handle: "CryptoKaleo", label: "caller · Kaleo" },
  { handle: "inversebrah", label: "KOL" },
  { handle: "CryptoCred", label: "trader" },
  { handle: "HsakaTrades", label: "trader · Hsaka" },
  { handle: "notthreadguy", label: "KOL" },
  { handle: "theunipcs", label: "caller · Bonk guy" },
  { handle: "CryptoGodJohn", label: "caller" },
  { handle: "frankdegods", label: "founder/KOL · DeGods" },
  { handle: "GiganticRebirth", label: "trader · GCR" },
  { handle: "Pentosh1", label: "trader" },
  { handle: "TheCryptoDog", label: "trader" },
  { handle: "Tetranode", label: "whale" },
  { handle: "DeFiGod1", label: "trader" },
  { handle: "gainzy222", label: "trader" },
  { handle: "AltcoinPsycho", label: "trader" },
  { handle: "smallcapscience", label: "KOL" },
  { handle: "SmartestMoney_", label: "trader" },
  { handle: "CredibleCrypto", label: "trader" },
  { handle: "CryptoMessiah", label: "trader" },
  { handle: "IamNomad", label: "trader" },
  { handle: "AltcoinGordon", label: "KOL" },
  { handle: "CryptoTony__", label: "trader" },
  { handle: "rektcapital", label: "analyst" },
  { handle: "CryptoDonAlt", label: "trader · DonAlt" },
  { handle: "koroushak", label: "trader" },
  { handle: "TheFlowHorse", label: "trader · Flood" },
  { handle: "MacnBTC", label: "trader" },
  { handle: "0xWangarian", label: "trader" },
  { handle: "IncomeSharks", label: "trader" },
  { handle: "PostyXBT", label: "trader" },
  { handle: "0x_Kun", label: "trader" },
  { handle: "cobie", label: "trader · Cobie" },
  { handle: "0xSisyphus", label: "trader" },
  { handle: "loomdart", label: "trader" },
  { handle: "shahh", label: "trader" },
  { handle: "CL207", label: "trader" },
  { handle: "satsdart", label: "trader" },
  { handle: "cozypront", label: "trader" },
  { handle: "0xngmi", label: "founder/analyst" },
  { handle: "eth_daddy", label: "trader" },
  { handle: "ThinkingUSD", label: "trader · Flood" },
  { handle: "poordart", label: "trader" },
  { handle: "gainzy", label: "trader" },
  { handle: "hentaavi", label: "trader" },
  { handle: "iloveponzi", label: "trader" },
  { handle: "mesawine1", label: "trader" },
  { handle: "0xShual", label: "trader" },
  { handle: "greg16676935420", label: "KOL · Greg" },
  { handle: "notlarrylink", label: "KOL" },
  { handle: "chooserich", label: "KOL" },
  { handle: "traderpow", label: "trader" },
  { handle: "MoonOverlord", label: "trader" },
  { handle: "cryptoyieldinfo", label: "analyst" },
  { handle: "TashaKKK", label: "KOL" },
  { handle: "zoomerfren", label: "KOL" },

  // ── Protocols / infra (official accounts) ─────────────────────────────────
  { handle: "solana", label: "infra · Solana" },
  { handle: "ethereum", label: "infra · Ethereum" },
  { handle: "base", label: "infra · Base" },
  { handle: "arbitrum", label: "infra · Arbitrum" },
  { handle: "optimism", label: "infra · Optimism" },
  { handle: "0xPolygon", label: "infra · Polygon" },
  { handle: "avax", label: "infra · Avalanche" },
  { handle: "Uniswap", label: "protocol · Uniswap" },
  { handle: "aave", label: "protocol · Aave" },
  { handle: "chainlink", label: "infra · Chainlink" },
  { handle: "MakerDAO", label: "protocol · Maker/Sky" },
  { handle: "LidoFinance", label: "protocol · Lido" },
  { handle: "eigenlayer", label: "protocol · EigenLayer" },
  { handle: "pumpdotfun", label: "infra · Pump.fun" },
  { handle: "jito_sol", label: "infra · Jito" },
  { handle: "heliuslabs", label: "infra · Helius" },
  { handle: "JupiterExchange", label: "protocol · Jupiter" },
  { handle: "RaydiumProtocol", label: "protocol · Raydium" },
  { handle: "DriftProtocol", label: "protocol · Drift" },
  { handle: "KaminoFinance", label: "protocol · Kamino" },
  { handle: "MarginFi", label: "protocol · marginfi" },
  { handle: "tensor_hq", label: "protocol · Tensor" },
  { handle: "MagicEden", label: "protocol · Magic Eden" },
  { handle: "phantom", label: "infra · Phantom" },
  { handle: "MetaMask", label: "infra · MetaMask" },
  { handle: "dYdX", label: "protocol · dYdX" },
  { handle: "GMX_IO", label: "protocol · GMX" },
  { handle: "PendleIntern", label: "protocol · Pendle" },
  { handle: "ethena_labs", label: "protocol · Ethena" },
  { handle: "MorphoLabs", label: "protocol · Morpho" },
  { handle: "CurveFinance", label: "protocol · Curve" },
  { handle: "convexfinance", label: "protocol · Convex" },
  { handle: "friedtech", label: "infra" },
  { handle: "monad_xyz", label: "infra · Monad" },
  { handle: "berachain", label: "infra · Berachain" },
  { handle: "SuiNetwork", label: "infra · Sui" },
  { handle: "Aptos", label: "infra · Aptos" },
  { handle: "celestia", label: "infra · Celestia" },
  { handle: "hyperliquid_x", label: "protocol · Hyperliquid" },
  { handle: "VirtualsProtocol", label: "protocol · Virtuals" },

  // ── Exchanges ─────────────────────────────────────────────────────────────
  { handle: "coinbase", label: "exchange · Coinbase" },
  { handle: "binance", label: "exchange · Binance" },
  { handle: "krakenfx", label: "exchange · Kraken" },
  { handle: "okx", label: "exchange · OKX" },
  { handle: "Bybit_Official", label: "exchange · Bybit" },
  { handle: "coinbasewallet", label: "infra · Coinbase Wallet" },
  { handle: "brian_armstrong", label: "founder · Coinbase" },
  { handle: "cz_binance", label: "founder · Binance" },
  { handle: "cryptohayes", label: "founder · BitMEX (Arthur Hayes)" },
  { handle: "SBF_FTX", label: "founder · FTX (defunct)" },
  { handle: "jespow", label: "founder · Kraken" },
  { handle: "tyler", label: "founder · Gemini (Winklevoss)" },
  { handle: "cameron", label: "founder · Gemini (Winklevoss)" },

  // ── Researchers / analysts / media / security ─────────────────────────────
  { handle: "MessariCrypto", label: "research · Messari" },
  { handle: "DelphiDigital", label: "research · Delphi" },
  { handle: "tokenterminal", label: "research · Token Terminal" },
  { handle: "DefiLlama", label: "data · DefiLlama" },
  { handle: "nansen_ai", label: "data · Nansen" },
  { handle: "ArkhamIntel", label: "data · Arkham" },
  { handle: "lookonchain", label: "on-chain analyst" },
  { handle: "spotonchain", label: "on-chain analyst" },
  { handle: "zachxbt", label: "investigator · ZachXBT" },
  { handle: "tayvano_", label: "security · MyCrypto (Tay)" },
  { handle: "officer_cia", label: "security researcher" },
  { handle: "samczsun", label: "security · Paradigm" },
  { handle: "bantg", label: "engineer · Yearn" },
  { handle: "peckshield", label: "security · PeckShield" },
  { handle: "CertiK", label: "security · CertiK" },
  { handle: "RugDocIO", label: "security · RugDoc" },
  { handle: "WatcherGuru", label: "media" },
  { handle: "Cointelegraph", label: "media" },
  { handle: "CoinDesk", label: "media" },
  { handle: "TheBlock__", label: "media · The Block" },
  { handle: "BanklessHQ", label: "media · Bankless" },
  { handle: "laurashin", label: "media · Unchained" },
  { handle: "wublockchain", label: "media · Wu Blockchain" },
  { handle: "DegenerateNews", label: "media" },
  { handle: "unusual_whales", label: "data/flow" },

  // ── Expansion batch: more founders / L1-L2 leaders ────────────────────────
  { handle: "zhuoxun_yin", label: "founder · Manta" },
  { handle: "0xkyle__", label: "researcher" },
  { handle: "dabit3", label: "developer advocate (Nader)" },
  { handle: "austingriffith", label: "builder · Ethereum (scaffold-eth)" },
  { handle: "PatrickAlphaC", label: "developer educator" },
  { handle: "hudsonjameson", label: "Ethereum community" },
  { handle: "vladtenev", label: "founder · Robinhood" },
  { handle: "jack", label: "founder · Block/Twitter" },
  { handle: "elonmusk", label: "founder · Tesla/X" },
  { handle: "saylor", label: "founder · MicroStrategy (Michael Saylor)" },
  { handle: "APompliano", label: "investor · Pomp" },
  { handle: "TylerDurden", label: "media · ZeroHedge" },
  { handle: "DavidGokhshtein", label: "KOL · Gokhshtein" },
  { handle: "scottmelker", label: "KOL · Wolf of All Streets" },
  { handle: "TheCryptoLark", label: "KOL · Lark Davis" },
  { handle: "IvanOnTech", label: "KOL · Ivan" },
  { handle: "AltCryptoGems", label: "KOL" },
  { handle: "CryptoWendyO", label: "KOL" },
  { handle: "girlgone_crypto", label: "KOL" },
  { handle: "CryptoTubers", label: "KOL" },
  { handle: "PeterLBrandt", label: "trader · legacy TA" },
  { handle: "cryptomanran", label: "KOL" },
  { handle: "EllioTrades", label: "KOL" },
  { handle: "sassal0x", label: "Ethereum advocate" },
  { handle: "milesdeutscher", label: "KOL · analyst" },
  { handle: "CryptoBusy", label: "KOL" },
  { handle: "Ashcryptoreal", label: "KOL" },
  { handle: "cobie", label: "trader · Cobie" },
  { handle: "0xLouisT", label: "founder/investor" },
  { handle: "DeFianceCapital", label: "fund · DeFiance" },
  { handle: "arthur_0x", label: "founder · DeFiance (Arthur Cheong)" },
  { handle: "ThreeSigmaXYZ", label: "research · Three Sigma" },
  { handle: "tokenbrice", label: "DeFi analyst" },
  { handle: "DefiIgnas", label: "DeFi researcher" },
  { handle: "thedefiedge", label: "DeFi researcher" },
  { handle: "Dynamo_Patrick", label: "DeFi researcher" },
  { handle: "korpi87", label: "DeFi researcher" },
  { handle: "0xLoke", label: "DeFi researcher" },
  { handle: "0x_Todd", label: "researcher" },
  { handle: "route2fi", label: "DeFi researcher" },
  { handle: "stacy_muur", label: "DeFi researcher" },
  { handle: "TheDeFiSaint", label: "DeFi analyst" },
  { handle: "0xMinion", label: "researcher" },
  { handle: "MrBlocks_", label: "researcher" },
  { handle: "Flowslikeosmo", label: "researcher" },
  { handle: "CryptoKoryo", label: "data analyst" },
  { handle: "0xfoobar", label: "engineer/researcher" },
  { handle: "cygaar_dev", label: "engineer" },
  { handle: "pcaversaccio", label: "security engineer" },
  { handle: "brockelmore", label: "engineer · Paradigm" },
  { handle: "andyfeng21", label: "founder · EigenLayer" },
  { handle: "ryanberckmans", label: "researcher" },
  { handle: "poopmandefi", label: "trader" },
  { handle: "yashhsm", label: "trader" },
  { handle: "0xdoge_", label: "trader" },
  { handle: "0xraceralt", label: "trader" },
  { handle: "0xSweep", label: "trader" },
  { handle: "cryptorinweb3", label: "KOL" },
  { handle: "moon_shiller", label: "KOL" },
  { handle: "0xUnihax0r", label: "trader" },
  { handle: "himgajria", label: "investor" },
  { handle: "lightcrypto", label: "trader" },
  { handle: "gainzy222", label: "trader" },
  { handle: "0xTindorr", label: "trader" },
  { handle: "0xngmi", label: "founder · DefiLlama" },
  { handle: "adamscochran", label: "investor · Cinneamhain" },
  { handle: "TheOneandOmsy", label: "trader" },
  { handle: "ColeGarnerHODL", label: "analyst" },
  { handle: "checkmatey_", label: "on-chain analyst · Glassnode" },
  { handle: "_Checkmatey", label: "on-chain analyst" },
  { handle: "glassnode", label: "data · Glassnode" },
  { handle: "santimentfeed", label: "data · Santiment" },
  { handle: "intotheblock", label: "data · IntoTheBlock" },
  { handle: "coinmetrics", label: "data · Coin Metrics" },
  { handle: "nic__carter", label: "investor · Castle Island" },
  { handle: "lopp", label: "Bitcoin · Jameson Lopp" },
  { handle: "adam3us", label: "founder · Blockstream (Adam Back)" },
  { handle: "aantonop", label: "Bitcoin educator" },
  { handle: "pete_rizzo_", label: "Bitcoin historian" },
  { handle: "DocumentingBTC", label: "Bitcoin media" },
  { handle: "matt_odell", label: "Bitcoin · Odell" },
  { handle: "gladstein", label: "Bitcoin · HRF" },
  { handle: "prestonpysh", label: "investor · Bitcoin" },
  { handle: "dergigi", label: "Bitcoin author" },
  { handle: "TuurDemeester", label: "investor · Bitcoin" },
  { handle: "MartyBent", label: "Bitcoin · TFTC" },
  { handle: "Excellion", label: "Bitcoin · Samson Mow" },
  { handle: "ErikVoorhees", label: "founder · ShapeShift" },
  { handle: "brian_armstrong", label: "founder · Coinbase" },
  { handle: "haydenzadams", label: "founder · Uniswap" },
  { handle: "danheld", label: "Bitcoin educator" },
  { handle: "CryptoCobain", label: "trader · Cobie alt" },
];
