import type { IntelligenceSpineSnapshot } from "../intelligence/types";
import { PointInTimeIntelligencePanel } from "../components/PointInTimeIntelligencePanel";

const capturedAt = "2026-08-22T20:25:00.000Z";

const previewSnapshot: IntelligenceSpineSnapshot = {
  schemaVersion: 1,
  rulesetVersion: "argus-point-in-time-v1",
  mode: "point_in_time",
  scoringImpact: "none",
  subject: {
    key: "project:preview",
    label: "Example Protocol",
    forms: [
      { form: "protocol", evidenceState: "verified", sourceRefs: ["source:market"] },
      { form: "token", evidenceState: "verified", sourceRefs: ["source:market"] },
    ],
    archetypes: { state: "generic", primary: null, matches: [] },
  },
  captureWindow: { earliest: capturedAt, latest: capturedAt },
  sources: [{
    id: "source:market",
    inputPath: "projectToken.market",
    provider: "market-registry",
    title: "Saved market and supply record",
    sourceClass: "canonical_market_registry",
    evidenceState: "reported_context",
    sourceUrl: "https://example.com/market",
    capturedAt,
  }, {
    id: "source:holders",
    inputPath: "tokenHolders.distribution",
    provider: "holder-provider",
    title: "Saved holder distribution",
    sourceClass: "onchain_data_provider",
    evidenceState: "bounded",
    sourceUrl: "https://example.com/holders",
    capturedAt,
  }],
  measurements: [{
    id: "goplus_fired_contract_flag_count",
    domain: "control",
    label: "GoPlus contract or deployer flags that fired",
    unit: "count",
    entityKey: "token:preview",
    evidenceState: "reported_context",
    sourceRefs: ["source:market"],
    valueType: "number",
    value: 0,
  }, {
    id: "provider_named_creator_or_authority_pct",
    domain: "supply",
    label: "GoPlus-reported creator or authority wallet share",
    unit: "percent",
    entityKey: "token:preview",
    evidenceState: "reported_context",
    sourceRefs: ["source:holders"],
    valueType: "number",
    value: 0.12,
  }, {
    id: "top_holder_pct",
    domain: "supply",
    label: "Largest assessed wallet share",
    unit: "percent",
    entityKey: "token:preview",
    evidenceState: "bounded",
    sourceRefs: ["source:holders"],
    valueType: "number",
    value: 1.98,
  }, {
    id: "assessed_wallet_share_floor_pct",
    domain: "supply",
    label: "Minimum combined share across 6 assessed wallets",
    unit: "percent",
    entityKey: "token:preview",
    evidenceState: "bounded",
    sourceRefs: ["source:holders"],
    valueType: "number",
    value: 5.8,
  }, {
    id: "project_strength_max_score:p3-token-conduct",
    domain: "supply",
    label: "P3_token_conduct deterministic evidence-band maximum",
    unit: "count",
    entityKey: "project:preview",
    evidenceState: "reported_context",
    sourceRefs: ["source:market"],
    valueType: "number",
    value: 16,
  }, {
    id: "project_strength_tier:p3-token-conduct",
    domain: "supply",
    label: "P3_token_conduct deterministic scorer-packet evidence tier",
    unit: "text",
    entityKey: "project:preview",
    evidenceState: "reported_context",
    sourceRefs: ["source:market"],
    valueType: "text",
    value: "solid",
  }, {
    id: "circulating_share_of_total_supply_pct",
    domain: "supply",
    label: "Reported circulating share of total supply",
    unit: "percent",
    entityKey: "token:preview",
    evidenceState: "reported_context",
    sourceRefs: ["source:market"],
    valueType: "number",
    value: 56,
  }, {
    id: "circulating_supply",
    domain: "supply",
    label: "Reported circulating supply",
    unit: "count",
    entityKey: "token:preview",
    evidenceState: "reported_context",
    sourceRefs: ["source:market"],
    valueType: "number",
    value: 1_521_215_580,
  }, {
    id: "holder_count",
    domain: "supply",
    label: "Reported holder count",
    unit: "count",
    entityKey: "token:preview",
    evidenceState: "bounded",
    sourceRefs: ["source:holders"],
    valueType: "number",
    value: 27_656,
  }, {
    id: "total_supply",
    domain: "supply",
    label: "Reported total supply",
    unit: "count",
    entityKey: "token:preview",
    evidenceState: "reported_context",
    sourceRefs: ["source:market"],
    valueType: "number",
    value: 2_716_547_718,
  }],
  questions: [{
    id: "question:security-audits",
    domain: "security",
    prompt: "Which independent security audits or reviews are published?",
    materiality: "critical",
    state: "unresolved",
    basis: "No independently bound audit document was saved with this report.",
    answerRefs: [],
    sourceRefs: [],
  }, {
    id: "question:treasury",
    domain: "treasury",
    prompt: "Who controls the treasury and what assets does it hold?",
    materiality: "critical",
    state: "not_collected",
    basis: "No identity-bound treasury register was collected.",
    answerRefs: [],
    sourceRefs: [],
  }],
  coverage: [{
    domain: "supply",
    state: "reported",
    measurementIds: ["total_supply", "circulating_supply", "holder_count"],
    questionIds: [],
    detail: "Supply and holder figures were saved with source attribution.",
  }],
  signals: [{
    id: "signal:integrity",
    ruleId: "intelligence-integrity-gate",
    ruleVersion: 1,
    kind: "coverage_gap",
    domain: "identity",
    severity: "high",
    polarity: "unknown",
    headline: "Part of the derived intelligence failed its lineage contract",
    finding: "The final integrity gate recorded 3 fail-closed integrity events.",
    whyItMatters: "A polished conclusion is not auditable when its source cannot be resolved exactly.",
    changeCondition: "Repair the saved source references and create a new report.",
    evidenceState: "bounded",
    measurementRefs: [],
    sourceRefs: [],
    lenses: ["investment", "alpha_research", "counterparty", "general_diligence"],
  }, {
    id: "signal:treasury",
    ruleId: "treasury-gap-at-scale",
    ruleVersion: 1,
    kind: "coverage_gap",
    domain: "treasury",
    severity: "medium",
    polarity: "unknown",
    headline: "The full treasury question remains open at material project scale",
    finding: "The saved report does not identify a complete treasury asset and control register.",
    whyItMatters: "Treasury concentration and spending authority can change runway and counterparty risk.",
    changeCondition: "Identity-bound treasury addresses, assets, liabilities, and control rights are measured.",
    evidenceState: "bounded",
    measurementRefs: [],
    sourceRefs: [],
    lenses: ["investment", "counterparty", "general_diligence"],
  }],
  lenses: ["investment", "alpha_research", "counterparty", "general_diligence"].map((id) => ({
    id: id as "investment" | "alpha_research" | "counterparty" | "general_diligence",
    label: id === "alpha_research" ? "Alpha research" : id === "general_diligence" ? "General diligence" : id[0].toUpperCase() + id.slice(1),
    question: id === "investment" ? "What could change an investment decision?" : "What matters most in this view?",
    domainPriority: id === "investment" ? ["security", "treasury", "supply", "identity"] : ["identity", "supply", "treasury", "security"],
    signalIds: ["signal:integrity", "signal:treasury"],
    unresolvedQuestionIds: ["question:security-audits", "question:treasury"],
    changeConditions: ["A published independent audit or identity-bound treasury register is added."],
  })),
};

export function IntelligenceReportPreview() {
  return (
    <main className="min-h-screen bg-void px-4 py-10 text-ink sm:px-8">
      <div className="mx-auto max-w-[1440px] rounded-xl border border-line bg-panel px-5 py-6 shadow-sm sm:px-8">
        <header className="border-b border-line/70 pb-5">
          <p className="eyebrow text-signal-lift">Saved report preview</p>
          <h1 className="display mt-1 text-[32px] text-ink">Example Protocol</h1>
          <p className="mt-2 text-[13.5px] text-ink-dim">Public Decision Intelligence presentation</p>
        </header>
        <PointInTimeIntelligencePanel snapshot={previewSnapshot} governingVerdict="CAUTION" />
      </div>
    </main>
  );
}
