// The first-pass answer a pasted URL owes the analyst, built only from what
// ARGUS actually rendered plus the first-party links on that page:
//
//   1. what this is (fund, token project, product, studio, parked, blocked,
//      coming soon), with the phrase the site used to say so;
//   2. whether the site is live, JavaScript-only, read through the crawler,
//      parked, behind a bot wall, or unavailable;
//   3. which linked accounts are the project's OWN (host or brand affinity, a
//      first-party cue, or the only account of its kind on the page) versus
//      accounts the page merely links (a portfolio company, a partner, a
//      person's own profile);
//   4. one plain-language line: who they say they are;
//   5. the one next step that is actually bound by the page. No button ever
//      launches a scan on a handle or contract the page did not link.
//
// Everything is deterministic and keyless. Nothing here is fetched.
import type { NamedPerson } from "./roster";
import type { Retrieval } from "./retrieve";
import type { OnChainPivot } from "./onchain";
import type { Recon } from "./recon";

// Strong, first-party evidence that THIS site is the token project (not just
// keyword noise): an explicit token launch/economics claim or a $-ticker/contract.
export const STRONG_TOKEN = /\b(tokenomics|total supply|circulating supply|max supply|\bTGE\b|fair launch|token sale|presale|airdrop|buy \$?[A-Z]{2,8}\b|our token)\b|0x[a-fA-F0-9]{40}/i;

export type SiteKind = "fund" | "token-project" | "product" | "studio" | "parked" | "blocked" | "coming-soon" | "unclassified";
export type SiteAvailability = "live" | "js-app" | "crawler-read" | "parked" | "blocked" | "coming-soon" | "unavailable";
export type SocialPlatform = "x" | "telegram" | "discord" | "github" | "linkedin" | "youtube" | "medium" | "farcaster" | "instagram" | "other";
export type AccountBasis = "host-match" | "brand-match" | "first-party-cue" | "sole-link" | "linked" | "person-profile";

export interface SiteAccount {
  platform: SocialPlatform;
  label: string;
  url: string;
  handle: string | null;
  basis: AccountBasis;
  /** Plain-language reason the account is or is not counted as the project's own. */
  why: string;
}

export type NextStep =
  | { kind: "token"; ref: string; label: string; reason: string }
  | { kind: "handle"; ref: string; label: string; reason: string }
  | { kind: "none"; reason: string };

export interface SiteProfile {
  kind: SiteKind;
  /** The site's own words that drove the classification, or null. */
  kindEvidence: string | null;
  availability: SiteAvailability;
  availabilityNote: string;
  brand: string | null;
  /** The sentence in which the site says what it is, verbatim, or null. */
  selfDescription: string | null;
  /** One plain-language line: what this is, in the site's own terms. */
  summary: string;
  officialAccounts: SiteAccount[];
  linkedAccounts: SiteAccount[];
  people: NamedPerson[];
  nextStep: NextStep;
  /** Distinct first-party identity signals present: self-description, named people, official accounts, docs/code. */
  identitySignals: number;
}

export interface ProfileInput {
  retrieval: Retrieval;
  socials: { label: string; url: string }[];
  people: NamedPerson[];
  isFund: boolean;
  strongToken: boolean;
  tokenSignalCount: number;
  content: string;
  pivot?: OnChainPivot;
}

// ---- page states that are not a project ----
const BOT_WALL = /\bjust a moment\b|checking your browser|verify(?:ing)? (?:that )?you are (?:a )?human|enable javascript and cookies to continue|attention required!?\s*\|?\s*cloudflare|\bray id\b|access denied\b|error 1020\b|complete the security check|ddos protection by|are you a robot|captcha|请稍候|please wait while we verify|bot detection/i;
const PARKED = /domain (?:is|may be) for sale|buy this domain|this domain is parked|parked free,? courtesy of|domain parking|sedo(?:parking)?\b|hugedomains|afternic|\bdan\.com\b|godaddy\.com\/domainsearch|this web ?page was generated by the domain owner|related searches|domain name is for sale|make an offer on this domain|namecheap parking|\bparked domain\b|get this domain|purchase this domain/i;
const COMING_SOON = /\bcoming soon\b|\blaunching soon\b|\bunder construction\b|\bstay tuned\b|\bwebsite (?:is )?(?:coming|launching) soon\b|\bbe the first to know\b|\bsomething (?:big|new) is coming\b/i;

// ---- kind self-descriptions (the site's own claim, quoted back) ----
const FUND_SELF = /\b(?:venture capital|vc firm|venture (?:fund|firm|partners)|(?:crypto|web3|digital[- ]asset|seed|growth|liquid|opportunity) fund|investment (?:firm|fund|manager|vehicles?|bank)|asset management|merchant bank|hedge fund|family office|private equity|private credit|we (?:invest|back) in?|portfolio compan(?:y|ies)|limited partners|\bLPs\b|\bAUM\b|assets under management|accelerator|incubator|angel (?:investor|fund|network)|capital (?:firm|partners|management)|fund (?:i|ii|iii|iv|v)\b|early[- ]stage (?:investor|fund)|invest(?:s|ing)? in (?:early|seed|pre-seed|founders|startups|companies))/i;

// "Backed by leading venture capital firms" is a token project describing its
// investors, not a fund describing itself. Fund phrases a backing preamble
// introduces are skipped; the first one the site applies to itself counts.
const BACKING_PREAMBLE = /(?:backed|supported|funded|invested|financed) by|investors? (?:include|such as|like)|our (?:investors|backers|partners)|raised (?:from|by)|partners? (?:include|such as)|led by|with support from/i;

// The broad fund gate that decides whether a site is reality-checked as a
// token at all. Kept broad on purpose: a fund must never be judged by a random
// same-ticker DEX coin. The one carve-out is a backing preamble, because
// "backed by leading venture capital firms" is a token project's investor line,
// not a fund describing itself, and it was suppressing the on-chain check.
const FUND_SITE = /\b(venture capital|ventures\b|\bvc\b|\bfund\b|\bfunds\b|capital\b|investment (?:firm|fund|dao)|portfolio compan|we (?:invest|back)|backing founders|accelerator|incubator|advisory|angel (?:investor|fund)|research (?:collective|studio))\b/i;

export function selfDescribesAsFund(content: string, title?: string | null): boolean {
  if (title && FUND_SITE.test(title)) return true;
  const re = new RegExp(FUND_SITE.source, "gi");
  let m: RegExpExecArray | null;
  let tries = 0;
  while ((m = re.exec(content)) && tries++ < 12) {
    const before = content.slice(Math.max(0, m.index - 60), m.index);
    if (!BACKING_PREAMBLE.test(before)) return true;
  }
  return false;
}
const STUDIO_SELF = /\b(?:venture studio|design studio|development studio|web3 studio|product studio|creative studio|(?:digital|software|blockchain|web3|crypto|marketing|design) agency|we build products|(?:software|blockchain|smart[- ]contract) (?:development|consultancy|consulting)|dev shop|we help (?:teams|companies|founders) (?:build|launch|ship))\b/i;
const PRODUCT_CUE = /\b(?:launch app|open app|get started|sign up|start (?:free|building)|pricing|download|api|docs|documentation|dashboard|platform|protocol|wallet|exchange|marketplace|app store|google play|integrations?|sdk|mainnet|testnet|bridge|swap|stake)\b/i;

const NOISE_SENTENCE = /cookie|javascript|browser|privacy policy|terms of|all rights reserved|©|registered trademark|\btrademarks?\b|member (?:of )?finra|securities transactions|not (?:an offer|investment advice)|for informational purposes/i;

function hostOf(url: string): string {
  try { return new URL(url).hostname.replace(/^www\./i, "").toLowerCase(); } catch { return url.toLowerCase(); }
}

const key = (s: string) => s.toLowerCase().replace(/[^a-z0-9]/g, "");

/** The brand, from the title's first segment when it is short enough to be a name; else the host label. */
export function brandOf(retrieval: Retrieval): string | null {
  const title = (retrieval.title ?? "").replace(/\s+/g, " ").trim();
  const seg = title.split(/\s+[|–—:·]\s+|\s+-\s+/)[0]?.trim() ?? "";
  if (seg.length >= 2 && seg.length <= 40 && !/[.!?]$/.test(seg) && seg.split(" ").length <= 6) return seg;
  const host = hostOf(retrieval.url);
  const label = host.split(".")[0] ?? "";
  return label.length >= 2 ? label : null;
}

// When the title gave nothing usable and the page opens "10X Capital is a…",
// the subject of that sentence is the brand as the site writes it, provided it
// agrees with the host label. Presentation only; matching still uses the key.
function refineBrand(brand: string | null, retrieval: Retrieval, selfDescription: string | null): string | null {
  if (!selfDescription) return brand;
  const hostKey = key(hostOf(retrieval.url).split(".")[0] ?? "");
  if (brand && key(brand) !== hostKey) return brand;
  const subject = selfDescription.match(/^(.{2,40}?)\s+(?:is|are|builds|provides|helps|offers|enables|brings|makes|lets|powers|invests|backs|delivers|connects)\b/i)?.[1]?.trim();
  if (!subject) return brand;
  const k = key(subject);
  return k.length >= 3 && (k === hostKey || hostKey.includes(k) || k.includes(hostKey)) ? subject : brand;
}

// The sentence (or clause) the match sits in, snapped to the nearest sentence
// or line boundary so a quote does not begin mid-heading.
function quoteAround(content: string, index: number, length: number, pad = 110): string {
  const lo = Math.max(0, index - pad);
  const before = content.slice(lo, index);
  const boundary = Math.max(before.lastIndexOf(". "), before.lastIndexOf("\n"), before.lastIndexOf("! "), before.lastIndexOf("? "));
  const start = boundary >= 0 ? lo + boundary + (before[boundary] === "\n" ? 1 : 2) : lo;
  const hi = Math.min(content.length, index + length + pad);
  const after = content.slice(index + length, hi);
  const stop = after.search(/[.!?](?:\s|$)|\n/);
  const end = stop >= 0 ? index + length + stop + (after[stop] === "\n" ? 0 : 1) : hi;
  let q = content.slice(start, end).replace(/[\s*#>]+/g, " ").trim();
  if (boundary < 0 && lo > 0) q = "…" + q;
  if (stop < 0 && hi < content.length) q = q + "…";
  return q.length > 180 ? q.slice(0, 177).replace(/\s+\S*$/, "") + "…" : q;
}

/**
 * The sentence in which the site says what it is. Preference: a sentence that
 * opens with the brand and predicates it ("10X Capital is a next-generation
 * merchant bank…"); then the page's own meta description; then the first
 * "is a / are the" sentence near the top. Never a synthesized paraphrase.
 */
export function selfDescriptionOf(content: string, brand: string | null, description?: string | null): string | null {
  const head = content.slice(0, 6000)
    .replace(/!\[[^\]]*\]\([^)]*\)/g, " ")
    .replace(/\[([^\]]+)\]\([^)]*\)/g, "$1")
    .replace(/^[\s#*>-]+/gm, "")
    .replace(/[*_]{1,3}/g, "");
  const sentences = head.split(/(?<=[.!?])\s+|\n+/).map((s) => s.replace(/\s+/g, " ").trim()).filter((s) => s.length >= 25 && s.length <= 240 && !NOISE_SENTENCE.test(s));
  const brandKey = brand ? key(brand) : "";
  const PREDICATE = /\b(?:is|are|builds|provides|helps|offers|enables|brings|makes|lets|powers|invests|backs|delivers|connects)\b/i;
  if (brandKey.length >= 3) {
    const own = sentences.find((s) => key(s.slice(0, brand!.length + 4)).startsWith(brandKey) && PREDICATE.test(s));
    if (own) return own;
  }
  const meta = (description ?? "").replace(/\s+/g, " ").trim();
  if (meta.length >= 25) return meta.length > 240 ? meta.slice(0, 237).replace(/\s+\S*$/, "") + "…" : meta;
  const generic = sentences.slice(0, 40).find((s) => /\b(?:is|are) (?:a|an|the)\b/i.test(s) && /^[A-Z0-9]/.test(s));
  return generic ?? null;
}

// ---- accounts ----
const X_NOISE = /^(?:status|home|intent|share|i|hashtag|search|explore|login|signup|settings|messages|notifications|compose|privacy|tos)$/i;
const TG_NOISE = /^(?:share|joinchat|addstickers|proxy|s)$/i;
const GH_NOISE = /^(?:orgs|sponsors|topics|features|about|marketplace|explore|pricing|login|join|settings|apps|site)$/i;

export function classifyAccountUrl(url: string): { platform: SocialPlatform; handle: string | null; personProfile: boolean } {
  let u: URL;
  try { u = new URL(url); } catch { return { platform: "other", handle: null, personProfile: false }; }
  const host = u.hostname.replace(/^www\./i, "").toLowerCase();
  const segs = u.pathname.split("/").filter(Boolean);
  const first = segs[0] ?? "";
  if (host === "x.com" || host === "twitter.com" || host === "mobile.twitter.com") {
    const h = first.replace(/^@/, "");
    return { platform: "x", handle: h && !X_NOISE.test(h) && /^[A-Za-z0-9_]{2,30}$/.test(h) ? h : null, personProfile: false };
  }
  if (host === "t.me" || host === "telegram.me") {
    const h = first.replace(/^@/, "");
    return { platform: "telegram", handle: h && !TG_NOISE.test(h) && /^[A-Za-z0-9_]{3,40}$/.test(h) ? h : null, personProfile: false };
  }
  if (host === "discord.gg" || host === "discord.com" || host === "discordapp.com") {
    return { platform: "discord", handle: null, personProfile: false };
  }
  if (host === "github.com") {
    return { platform: "github", handle: first && !GH_NOISE.test(first) ? first : null, personProfile: false };
  }
  if (host === "linkedin.com" || host.endsWith(".linkedin.com")) {
    if (first === "company" || first === "school") return { platform: "linkedin", handle: segs[1] ?? null, personProfile: false };
    return { platform: "linkedin", handle: first === "in" ? segs[1] ?? null : null, personProfile: first === "in" };
  }
  if (host === "youtube.com" || host === "youtu.be") {
    const h = first.startsWith("@") ? first.slice(1) : first === "c" || first === "channel" || first === "user" ? segs[1] ?? null : null;
    return { platform: "youtube", handle: h, personProfile: false };
  }
  if (host === "medium.com" || host.endsWith(".medium.com")) {
    const sub = host.endsWith(".medium.com") ? host.replace(/\.medium\.com$/, "") : null;
    return { platform: "medium", handle: first.startsWith("@") ? first.slice(1) : sub, personProfile: false };
  }
  if (host === "warpcast.com" || host === "farcaster.xyz") return { platform: "farcaster", handle: first || null, personProfile: false };
  if (host === "instagram.com") return { platform: "instagram", handle: first || null, personProfile: false };
  return { platform: "other", handle: null, personProfile: false };
}

const PLATFORM_LABEL: Record<SocialPlatform, string> = {
  x: "X", telegram: "Telegram", discord: "Discord", github: "GitHub", linkedin: "LinkedIn",
  youtube: "YouTube", medium: "Medium", farcaster: "Farcaster", instagram: "Instagram", other: "link",
};

function affinity(handle: string, hostKey: string, brandKey: string): "host-match" | "brand-match" | null {
  const h = key(handle);
  if (h.length < 3) return null;
  const near = (a: string, b: string) => a === b || (a.length >= 4 && b.includes(a)) || (b.length >= 4 && a.includes(b));
  if (hostKey.length >= 4 && near(h, hostKey)) return "host-match";
  if (brandKey.length >= 4 && brandKey !== hostKey && near(h, brandKey)) return "brand-match";
  return null;
}

function looksLikePerson(handle: string, people: NamedPerson[]): boolean {
  const h = key(handle);
  if (h.length < 4) return false;
  return people.some((p) => {
    const parts = p.name.split(/\s+/).map(key).filter(Boolean);
    const first = parts[0] ?? "";
    const last = parts[parts.length - 1] ?? "";
    return h === key(p.name) || (last.length >= 5 && h.includes(last)) || (first.length >= 3 && last.length >= 3 && h.includes(first) && h.includes(last));
  });
}

const CUE = /follow(?:\s+us)?(?:\s+on)?|official(?:\s+account)?|our (?:x|twitter|telegram|discord|github|linkedin)|join (?:our|the) (?:community|telegram|discord)|community/i;

function hasCue(url: string, handle: string | null, content: string): boolean {
  const target = handle ? handle : url;
  const esc = target.replace(/[.*+?^${}()|[\]\\]/g, "\\$&");
  return new RegExp(`(?:${CUE.source})[^\\n]{0,40}${esc}`, "i").test(content);
}

export function classifyAccounts(
  socials: { label: string; url: string }[],
  retrieval: Retrieval,
  brand: string | null,
  people: NamedPerson[],
  content: string,
): { official: SiteAccount[]; linked: SiteAccount[] } {
  const hostKey = key(hostOf(retrieval.url).split(".")[0] ?? "");
  const brandKey = brand ? key(brand) : "";
  const rows = socials.map((s) => ({ ...s, ...classifyAccountUrl(s.url) }));
  const perPlatform = new Map<SocialPlatform, number>();
  for (const r of rows) perPlatform.set(r.platform, (perPlatform.get(r.platform) ?? 0) + 1);

  const official: SiteAccount[] = [];
  const linked: SiteAccount[] = [];
  for (const r of rows) {
    const label = r.handle ? (r.platform === "x" ? `@${r.handle}` : `${PLATFORM_LABEL[r.platform]} · ${r.handle}`) : PLATFORM_LABEL[r.platform] + (r.platform === "discord" ? " invite" : "");
    const base = { platform: r.platform, label, url: r.url, handle: r.handle };
    if (r.personProfile) {
      linked.push({ ...base, basis: "person-profile", why: "A personal profile, not the project's account." });
      continue;
    }
    // A named person's own handle can contain the brand ("samclutchfield" on
    // clutch.example); the person wins, because the page named them.
    if (r.handle && looksLikePerson(r.handle, people)) {
      linked.push({ ...base, basis: "person-profile", why: "Looks like a named team member's own account, not the project's." });
      continue;
    }
    const aff = r.handle ? affinity(r.handle, hostKey, brandKey) : null;
    if (aff) {
      official.push({ ...base, basis: aff, why: aff === "host-match" ? "Matches the site's own domain." : `Matches the site's brand name (${brand}).` });
      continue;
    }
    if (hasCue(r.url, r.handle, content)) {
      official.push({ ...base, basis: "first-party-cue", why: "The page frames it as its own (follow us / official / join our community)." });
      continue;
    }
    if ((perPlatform.get(r.platform) ?? 0) === 1 && r.platform !== "other") {
      official.push({ ...base, basis: "sole-link", why: `The only ${PLATFORM_LABEL[r.platform]} account the page links.` });
      continue;
    }
    linked.push({ ...base, basis: "linked", why: `One of several ${PLATFORM_LABEL[r.platform]} accounts on the page; the site does not claim it as its own.` });
  }
  return { official, linked };
}

// ---- assembly ----
const KIND_NOUN: Record<SiteKind, string> = {
  fund: "a fund / investment firm",
  "token-project": "a token project",
  product: "a product or protocol site",
  studio: "a studio / agency",
  parked: "a parked domain",
  blocked: "a bot-protection wall",
  "coming-soon": "a placeholder page",
  unclassified: "a site ARGUS could not classify from its own copy",
};

export const KIND_LABEL: Record<SiteKind, string> = {
  fund: "FUND / FIRM", "token-project": "TOKEN PROJECT", product: "PRODUCT", studio: "STUDIO",
  parked: "PARKED DOMAIN", blocked: "BLOCKED", "coming-soon": "COMING SOON", unclassified: "UNCLASSIFIED",
};

export const AVAILABILITY_LABEL: Record<SiteAvailability, string> = {
  live: "LIVE", "js-app": "LIVE · JS APP", "crawler-read": "LIVE · CRAWLER READ",
  parked: "PARKED", blocked: "BLOCKED", "coming-soon": "PLACEHOLDER", unavailable: "UNAVAILABLE",
};

function directOutcome(retrieval: Retrieval): string | null {
  return (retrieval.stages ?? []).find((s) => s.method === "direct fetch")?.outcome ?? null;
}

// The first fund phrase the site applies to itself (see BACKING_PREAMBLE).
function ownFundClaim(plain: string): RegExpExecArray | null {
  const re = new RegExp(FUND_SELF.source, "gi");
  let m: RegExpExecArray | null;
  let tries = 0;
  while ((m = re.exec(plain)) && tries++ < 8) {
    const before = plain.slice(Math.max(0, m.index - 60), m.index);
    if (!BACKING_PREAMBLE.test(before)) return m;
  }
  return null;
}

export function buildSiteProfile(input: ProfileInput): SiteProfile {
  const { retrieval, content, people } = input;
  let brand = brandOf(retrieval);
  const host = hostOf(retrieval.url);

  if (retrieval.status === "gap") {
    return {
      kind: "unclassified", kindEvidence: null, availability: "unavailable",
      availabilityNote: "ARGUS could not open or render the site. Nothing below is a claim about its content.",
      brand, selfDescription: null,
      summary: `${brand ?? host}: the site could not be opened, so ARGUS cannot say what it is.`,
      officialAccounts: [], linkedAccounts: [], people: [],
      nextStep: { kind: "none", reason: "Nothing was read from the page, so there is no account or contract to hand to a full investigation." },
      identitySignals: 0,
    };
  }

  const plain = content.replace(/!\[[^\]]*\]\([^)]*\)/g, " ");
  const thin = plain.length < 1500;

  // States that are not a project. Each is a real observation about the page.
  const wall = BOT_WALL.exec(plain);
  if (wall && plain.length < 2500) {
    return {
      kind: "blocked", kindEvidence: quoteAround(plain, wall.index, wall[0].length), availability: "blocked",
      availabilityNote: "The URL answered with a bot-protection challenge, not the site. ARGUS never saw the real page.",
      brand, selfDescription: null,
      summary: `${brand ?? host}: the page returned a bot-protection challenge (“${wall[0]}”), so ARGUS could not read the site.`,
      officialAccounts: [], linkedAccounts: [], people: [],
      nextStep: { kind: "none", reason: "A challenge page links nothing of the project's. Retry later or paste the project's account or contract directly." },
      identitySignals: 0,
    };
  }
  const parked = PARKED.exec(plain);
  if (parked && plain.length < 3500) {
    return {
      kind: "parked", kindEvidence: quoteAround(plain, parked.index, parked[0].length), availability: "parked",
      availabilityNote: "This is a domain parking / for-sale page. No project is being served at this URL.",
      brand, selfDescription: null,
      summary: `${host} is a parked domain (“${parked[0]}”). There is no project here to assess.`,
      officialAccounts: [], linkedAccounts: [], people: [],
      nextStep: { kind: "none", reason: "A parked domain links no project accounts. If a project claims this URL, that claim is the finding." },
      identitySignals: 0,
    };
  }
  const soon = COMING_SOON.exec(plain);
  if (soon && thin && people.length === 0) {
    const accounts = classifyAccounts(input.socials, retrieval, brand, people, content);
    return {
      kind: "coming-soon", kindEvidence: quoteAround(plain, soon.index, soon[0].length), availability: "coming-soon",
      availabilityNote: "A placeholder page. The site is live but shows no product, team, or documentation yet.",
      brand, selfDescription: selfDescriptionOf(plain, brand, retrieval.description),
      summary: `${brand ?? host} is a placeholder page (“${soon[0]}”). Nothing here can be verified yet.`,
      officialAccounts: accounts.official, linkedAccounts: accounts.linked, people: [],
      nextStep: nextStepOf(accounts.official, input.pivot, "coming-soon"),
      identitySignals: accounts.official.length ? 1 : 0,
    };
  }

  const availability: SiteAvailability = retrieval.status === "rendered"
    ? "live"
    : directOutcome(retrieval) === "spa-stub" ? "js-app" : "crawler-read";
  const availabilityNote = availability === "live"
    ? "Live. Server-rendered HTML was read directly."
    : availability === "js-app"
      ? "Live, but JavaScript-only: the server sends no content without a browser. ARGUS read it through the rendering crawler."
      : "Live. The direct fetch was blocked (cross-origin or network), so ARGUS read the page through the rendering crawler.";

  const selfDescription = selfDescriptionOf(plain, brand, retrieval.description);
  brand = refineBrand(brand, retrieval, selfDescription);
  const accounts = classifyAccounts(input.socials, retrieval, brand, people, content);

  let kind: SiteKind = "unclassified";
  let kindEvidence: string | null = null;
  const fundHit = ownFundClaim(plain);
  const studioHit = STUDIO_SELF.exec(plain);
  const contractOnPage = input.pivot?.attempted && input.pivot.method === "contract-on-page" && !!input.pivot.found;
  if (!input.isFund && (contractOnPage || (input.strongToken && input.tokenSignalCount >= 2))) {
    kind = "token-project";
    kindEvidence = contractOnPage
      ? `Links its token contract on the page (${input.pivot!.found!.symbol}).`
      : `Makes first-party token claims${input.pivot?.claim.ticker ? ` (${input.pivot.claim.ticker})` : ""}: tokenomics, supply, sale, or airdrop copy.`;
  } else if (fundHit && (input.isFund || fundHit.index < 4000)) {
    kind = "fund";
    kindEvidence = quoteAround(plain, fundHit.index, fundHit[0].length);
  } else if (studioHit) {
    kind = "studio";
    kindEvidence = quoteAround(plain, studioHit.index, studioHit[0].length);
  } else if (plain.length >= 400 && PRODUCT_CUE.test(plain)) {
    kind = "product";
    const cues = [...new Set((plain.match(new RegExp(PRODUCT_CUE.source, "gi")) ?? []).map((c) => c.toLowerCase()))].slice(0, 5);
    kindEvidence = `Product-site cues on the page: ${cues.join(", ")}.`;
  }

  const hasDocs = input.socials.some((s) => /github\.com\//i.test(s.url)) || /\b(?:docs|documentation|whitepaper|litepaper|gitbook)\b/i.test(plain);
  const identitySignals = (selfDescription ? 1 : 0) + (people.length ? 1 : 0) + (accounts.official.length ? 1 : 0) + (hasDocs ? 1 : 0);

  const who = brand ?? host;
  const summary = selfDescription
    ? `${who} says it is ${KIND_NOUN[kind]}: “${selfDescription}”`
    : `${who} reads as ${KIND_NOUN[kind]}, but the rendered page never says what it is in plain language.`;

  return {
    kind, kindEvidence, availability, availabilityNote, brand, selfDescription, summary,
    officialAccounts: accounts.official, linkedAccounts: accounts.linked, people,
    nextStep: nextStepOf(accounts.official, input.pivot, kind),
    identitySignals,
  };
}

/**
 * The profile for any recon, including records saved before profiles existed:
 * those are rebuilt from the stored retrieval, socials, and names, so an old
 * report still answers what-is-this / is-it-live / which-accounts-are-official.
 */
export function profileOf(recon: Recon): SiteProfile {
  if (recon.profile) return recon.profile;
  const people: NamedPerson[] = recon.team.people ?? recon.team.names.map((name) => ({ name, role: null, basis: "inline-role" as const }));
  const content = recon.retrieval.content ?? "";
  return buildSiteProfile({
    retrieval: recon.retrieval,
    socials: recon.socials,
    people,
    isFund: !!recon.isFund,
    strongToken: STRONG_TOKEN.test(content),
    tokenSignalCount: recon.tokenSignals.length,
    content,
    pivot: recon.pivot,
  });
}

function nextStepOf(official: SiteAccount[], pivot: OnChainPivot | undefined, kind: SiteKind): NextStep {
  if (pivot?.attempted && pivot.method === "contract-on-page" && pivot.found) {
    return {
      kind: "token", ref: pivot.found.address,
      label: `Open the full token audit for ${pivot.found.symbol}`,
      reason: "The page links this contract itself, so the on-chain audit is bound to this site.",
    };
  }
  const x = official.find((a) => a.platform === "x" && a.handle);
  if (x?.handle) {
    return {
      kind: "handle", ref: `@${x.handle}`,
      label: `Run full ARGUS on @${x.handle}`,
      reason: `${x.why} A full account investigation resolves the people and history behind it.`,
    };
  }
  const base = kind === "fund"
    ? "No official X account is linked on the page, so there is no account to hand to a full investigation."
    : "No official X account or token contract is linked on the rendered page, so ARGUS will not launch a scan it cannot bind.";
  return { kind: "none", reason: `${base} Paste the account or contract to investigate it directly.` };
}
